INSERT INTO public.products (name, description, price, image_url, rating, tags, is_available) VALUES
('Mix Veg Momos', NULL, 80, '/cafe-items/snaks/mix veg momos.jpg', 4.5, ARRAY['Snacks'], true),
('Schezwan Momos', 'Spicy schezwan filling', 100, '/cafe-items/snaks/Schezwan Momos.jpg', 4.6, ARRAY['Snacks'], true),
('Corn & Cheese Momos', 'Melty cheese and sweet corn', 120, '/cafe-items/snaks/Corn Cheese Momos.jpg', 4.8, ARRAY['Snacks'], true),
('Paneer Momos', NULL, 140, '/cafe-items/snaks/Paneer Momos.jpg', 4.7, ARRAY['Snacks'], true),
('Paneer Tikka Momos', 'Crunchy paneer tikka style', 150, '/cafe-items/snaks/Paneer Tikka Momo.jpg', 4.8, ARRAY['Snacks'], true),
('French Fries', NULL, 60, '/cafe-items/snaks/french fries.jpg', 4.5, ARRAY['Snacks'], true),
('Chinese Fries', 'Saucy Indo-Chinese style', 100, '/cafe-items/snaks/chinese fries.jpg', 4.7, ARRAY['Snacks'], true),
('Popcorn Fries', NULL, 110, '/cafe-items/snaks/popcorn fries.jpg', 4.6, ARRAY['Snacks'], true),
('Masala Fries', 'Spicy Indian masala sprinkle', 70, '/cafe-items/snaks/masala fries.jpg', 4.5, ARRAY['Snacks'], true),
('Peri Peri Fries', 'Tangy & spicy peri peri', 90, '/cafe-items/snaks/peri peri fries.jpg', 4.7, ARRAY['Snacks'], true),
('Aloo Tikki Sandwich', NULL, 60, '/cafe-items/Sandwich/Aloo Tikki Sandwich.jpg', 4.4, ARRAY['Sandwich'], true),
('Aloo Tikki Cheese Sandwich', NULL, 70, '/cafe-items/Sandwich/Aloo Tikki chese sandwich.jpg', 4.6, ARRAY['Sandwich'], true),
('Veg Grill Sandwich', NULL, 80, '/cafe-items/Sandwich/veg grill sandwitch.jpg', 4.5, ARRAY['Sandwich'], true),
('Veg Cheese Grill Sandwich', NULL, 90, '/cafe-items/Sandwich/veg cheese grill Sandwich.jpg', 4.7, ARRAY['Sandwich'], true),
('Corn Cheese Grill Sandwich', NULL, 100, '/cafe-items/Sandwich/corn Cheese grill  Sandwiche.jpg', 4.8, ARRAY['Sandwich'], true),
('Paneer Cheese Grill Sandwich', NULL, 120, '/cafe-items/Sandwich/paneer Cheese grill Sandwich.jpg', 4.9, ARRAY['Sandwich'], true),
('Veg Burger', NULL, 70, '/cafe-items/burger/Veg Burger.jpg', 4.5, ARRAY['Burger'], true),
('Veg Cheese Burger', NULL, 80, '/cafe-items/burger/veg cheese Burger.jpg', 4.7, ARRAY['Burger'], true),
('Aloo Tikki Burger', NULL, 60, '/cafe-items/burger/Aloo tikki burger.jpg', 4.4, ARRAY['Burger'], true),
('Spicy Burger', NULL, 90, '/cafe-items/burger/Spicy  Burger.jpg', 4.6, ARRAY['Burger'], true),
('Double Tikki Cheese Burger', 'Double the patty, double the cheese', 110, '/cafe-items/burger/Double Tikki chese burger.jpg', 4.9, ARRAY['Burger'], true),
('Schezwan Pizza', NULL, 140, '/cafe-items/pizza/SCHEZWAN  PIZZA.jpg', 4.6, ARRAY['Pizza'], true),
('Paneer Pizza', NULL, 150, '/cafe-items/pizza/PANEER PIZZA.jpg', 4.7, ARRAY['Pizza'], true),
('Italian Pizza', NULL, 170, '/cafe-items/pizza/Italian Pizza.jpg', 4.8, ARRAY['Pizza'], true),
('Paneer Double Cheese Pizza', NULL, 190, '/cafe-items/pizza/Paneer Double Cheese Pizza.jpg', 4.9, ARRAY['Pizza'], true),
('Sweet Corn Double Cheese Pizza', NULL, 190, '/cafe-items/pizza/Sweet Corn Double Cheese Pizza.jpg', 4.8, ARRAY['Pizza'], true),
('Plain Cheese Pizza', NULL, 120, '/cafe-items/pizza/plain cheese pizza.jpg', 4.5, ARRAY['Pizza'], true),
('Sweet Corn Pizza', NULL, 130, '/cafe-items/pizza/sweet corn pizza.jpg', 4.6, ARRAY['Pizza'], true),
('Double Cheese Pizza', 'Extra loaded double cheese', 160, '/cafe-items/pizza/double cheese pizza.jpg', 4.7, ARRAY['Pizza'], true),
('Hot Coffee', NULL, 25, '/cafe-items/coffee/Hot Coffeen.jpg', 4.5, ARRAY['Coffee'], true),
('Cold Coffee (Plain)', NULL, 40, '/cafe-items/coffee/Cold Coffee (Plain).jpg', 4.6, ARRAY['Coffee'], true),
('Cold Coffee (Vanilla)', NULL, 70, '/cafe-items/coffee/Cold Coffee (Vanilla).jpg', 4.7, ARRAY['Coffee'], true),
('Cold Coffee (Crush)', NULL, 70, '/cafe-items/coffee/Cold Coffee (Crush).jpg', 4.7, ARRAY['Coffee'], true),
('Cold Coffee With Chocolate', 'With ice cream', 80, '/cafe-items/coffee/Cold Coffee with Chocolate Ice Cream.jpg', 4.8, ARRAY['Coffee'], true),
('Black Coffee', NULL, 25, '/cafe-items/coffee/Black Coffee.jpg', 4.6, ARRAY['Coffee'], true),
('Green Apple Mocktail', NULL, 80, '/cafe-items/Mocktails/Green Apple Mocktail.jpg', 4.7, ARRAY['Mocktail'], true),
('Blue Curacao Mocktail', NULL, 80, '/cafe-items/Mocktails/Blue Curacao Mocktail.jpg', 4.8, ARRAY['Mocktail'], true),
('Rose Mocktail', NULL, 80, '/cafe-items/Mocktails/Rose Mocktail.jpg', 4.6, ARRAY['Mocktail'], true);